#!/bin/sh

print_usage()
{
    echo "Use as below:"
    echo "     rebuild [c|cpp]"
}

if [ $# -ne 1 ]; then
    print_usage;
    exit 1;
fi

if [ $1 = "c" ]; then
    ctags-exuberant -R --c-kinds=+p --fields=+aS --extra=+q --sort=foldcase
    find $(pwd) -name "*.h" -o -name "*.c" -o -name "*.S" > cscope.files
elif [ $1 = "cpp" ]; then
    ctags-exuberant -R --c++-kinds=+p --fields=+iaS --extra=+q --langmap=c++:+.inl .
    find $(pwd) -name "*.h" -o -name "*.hpp" -o -name "*.cc" -o -name "*.cpp" -o -name "*.cxx"> cscope.files
else
    print_usage;
    exit 1;
fi

cscope -i cscope.files -Rbkq
